config/routes.rb
Rails.application.routes.draw do
  resources :kittens

  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kittens }
     end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kitten }
     end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.create(kittens_params)
    if @kitten.save
      flash[:notice] = "Kitten created successfully."
      redirect_to @kitten
    else
      flash[:notice] = "Error creating kitten."
      redirect_to new_kitten_path
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to(@kitten)
    else
      render "edit"
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy!
    flash[:notice] = "Your kitten has been deleted"
    redirect_to kittens_path
  end

  private

    def kittens_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_for(@kitten) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>
  <%= f.label :softness %>
  <%= f.text_field :softness %>
  <%= f.submit %>
<% end %>
<% if current_page?("kittens#edit") %>
  <%= link_to "Back", @kitten %>
<% else %>
  <%= link_to "Back", kittens_path %>
<% end %>
<%= link_to "Destroy", @kitten, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render "kitten_form" %>

app/views/kittens/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<table>
  <thead>
    <th>Name</th>
    <th>Age</th>
    <th>Cuteness</th>
    <th>Softness</th>
  </thead>
  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to "Show", kitten %></td>
        <td><%= link_to "Edit", edit_kitten_path(kitten) %></td>
        <td><%= link_to "Destroy", kitten, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render "kitten_form" %>

app/views/kittens/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<table>
  <thead>
    <th>Name</th>
    <th>Age</th>
    <th>Cuteness</th>
    <th>Softness</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @kitten.name %></td>
      <td><%= @kitten.age %></td>
      <td><%= @kitten.cuteness %></td>
      <td><%= @kitten.softness %></td>
      <td><%= link_to "Back", kittens_path %></td>
      <td><%= link_to "Edit", edit_kitten_path(@kitten) %></td>
      <td><%= link_to "Destroy", @kitten, method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>